{% set name = "fits2image" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fits2image-{{ version }}.tar.gz
  sha256: 0b1743cfd6f272f9df95a3fdb496f0a89fb5f8a29200db05d6f8f4ea63b7c304

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - astropy-base
    - pillow

test:
  imports:
    - fits2image
  commands:
    - pip check
  requires:
    - python  {{ python_min }}
    - pip

about:
  home: https://github.com/LCOGT/fits2image
  summary: Common libraries for the conversion and scaling of fits images
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - phycodurus
