{% set name = "fits2image" %}
{% set version = "0.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fits2image-{{ version }}.tar.gz
  sha256: 6b940ff4ac9a0f381e8a25cb8440723bfc85578f2671c50310d02e482eca06a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - astropy-base
    - pillow

test:
  imports:
    - fits2image
  commands:
    - pip check
  requires:
    - python  {{ python_min }}
    - pip

about:
  home: https://github.com/LCOGT/fits2image
  summary: Common libraries for the conversion and scaling of fits images
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - phycodurus
