{% set name = "fits2image" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/fits2image-{{ version }}.tar.gz
  sha256: e300dc5e44a2101bf1c7ea011ce0d914a395bf765188040ee76dd8accfee6ff9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - astropy-base
    - pillow

test:
  imports:
    - fits2image
  commands:
    - pip check
  requires:
    - python  {{ python_min }}
    - pip

about:
  home: https://github.com/LCOGT/fits2image
  summary: Common libraries for the conversion and scaling of fits images
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - phycodurus
